FROM ://microsoft.com AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM ://microsoft.com AS build
WORKDIR /src
COPY ["UserLogin.csproj", "."]
RUN dotnet restore "./UserLogin.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "UserLogin.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "UserLogin.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UserLogin.dll"]
