FROM ://microsoft.com AS build-env
WORKDIR /App

# सभी फाइलें कॉपी करें और प्रोजेक्ट को पब्लिश करें
COPY . ./
RUN dotnet publish -c Release -o out

# रनटाइम इमेज बनाएं
FROM ://microsoft.com
WORKDIR /App
COPY --from=build-env /App/out .

# 📌 यहाँ बस अपने प्रोजेक्ट का असली नाम लिख दें
ENTRYPOINT ["dotnet", "UserLogin.dll"]
